name: 'Run Tests'
run-name: '${{ github.actor }} is running tests...'
description: 'Setups CI/CD env and executes tests'

on: push

inputs:
  node_version:
    description: 'Node.js Version'
    required: true
    default: '20.9.0'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-director: './'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'actions/setup-node@v3'
        with:
          node_version: '${{inputs.node_version}}'
      - run: npm ci
      - run: npm test